[build]
  command = "npm install && npm run build"  # 安裝相依套件並建置專案
  publish = "build/"  # 指定建置完成後的檔案目錄
  functions = "line_weather"

[[edge_functions]]
function = "line-weather"
path = "/test"

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/line-weather"
  status = 200